title = "IoThings"
baseURL = "https://iothings.fr"
languageCode = "fr-fr"
theme = "ananke"

#sectionPagesMenu = "main"
[menu]
  [[menu.main]]
    identifier = "features"
    name = "Features"
    title = "Features"
    url = "/features/"
    weight = 10
  [[menu.main]]
    identifier = "documentation"
    name = "Docs"
    title = "Docs"
    url = "https://docs.iothings.fr"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 30
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = 40  
  [[menu.main]]
    identifier = "demo"
    name = "Demo"
    title = "Demo"
    url = "https://app.iothings.fr"
    weight = 40

[params]
  favicon = "favicons/favicon.ico"
  description = "IoT framework, at scale."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/IoThingsDev/api"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image = "/images/bridges-roads-min.png"
  recent_posts_number = 2